name: .NET

on:
  push:
    branches: 
    - master
  pull_request:
    branches: 
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore MSLogging.Extensions/MSLogging.Extensions.Caller
    - name: Build
      run: dotnet build MSLogging.Extensions/MSLogging.Extensions.Caller --no-restore
    - name: Test
      run: dotnet test MSLogging.Extensions/MSLogging.Extensions.Tests --no-build --verbosity normal
